version: '3.7'

services:
    web:
        build: ./src 
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        env_file: 
            - .env
        volumes: 
            - ./src/:/usr/src/app/
        ports: 
            - 8002:8000

    db:
        image: postgres:12.3-alpine
        hostname: postgresdocker
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        env_file: 
            - .env
        
    pgadmin:
        image: dpage/pgadmin4
        depends_on: 
            - db
        ports:
            - 5555:80
        env_file: 
            - .env

volumes:
    postgres_data: